-- Cupones de descuento por evento + IVA en el costo (aplicado 2026-07-10).
ALTER TABLE EVENTOS ADD (
  INCLUYE_IVA CHAR(1) DEFAULT 'N' CHECK (INCLUYE_IVA IN ('S','N')),
  MONTO_IVA   NUMBER
);

CREATE TABLE EVENTO_CUPONES (
  ID_CUPON        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_EVENTO       NUMBER NOT NULL,
  CODIGO          VARCHAR2(50) NOT NULL,
  MONTO_DESCUENTO NUMBER NOT NULL,
  ACTIVO          CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  FECHA_REGISTRO  DATE DEFAULT SYSDATE,
  CONSTRAINT FK_CUPON_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO),
  CONSTRAINT UQ_CUPON_EVENTO_CODIGO UNIQUE (ID_EVENTO, CODIGO)
);
-- La app móvil puede leer EVENTO_CUPONES (ACTIVO='S') para canjear códigos.
